"""complete baseline schema

Revision ID: 3d9ff268aeb3
Revises:
Create Date: 2026-09-08 00:22:19.032391
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "3d9ff268aeb3"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "agent_roles",
        sa.Column("id", sa.String(length=50), nullable=False),
        sa.Column("display_name", sa.String(length=100), nullable=False),
        sa.Column("perspective", sa.Text(), nullable=False),
        sa.Column("expertise_domains", sa.Text(), nullable=False),
        sa.Column("risk_appetite", sa.String(length=20), nullable=False),
        sa.Column("default_stance", sa.Text(), nullable=False),
        sa.Column("evidence_preference", sa.String(length=20), nullable=False),
        sa.Column("model_override", sa.String(length=100), nullable=False),
        sa.Column("background_brief", sa.Text(), nullable=False),
        sa.Column("prompt_template", sa.Text(), nullable=False),
        sa.Column("is_builtin", sa.Boolean(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("tenant_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("NOW()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("NOW()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_agent_roles_active", "agent_roles", ["is_active"], unique=False)
    op.create_index(op.f("ix_agent_roles_tenant_id"), "agent_roles", ["tenant_id"], unique=False)
    op.create_table(
        "api_keys",
        sa.Column(
            "provider",
            sa.String(length=50),
            nullable=False,
            comment="LLM厂商: siliconflow/deepseek/openai/openrouter/custom",
        ),
        sa.Column("name", sa.String(length=100), nullable=False, comment="Key别名（同一厂商可存多个）"),
        sa.Column("encrypted_key", sa.Text(), nullable=False),
        sa.Column("base_url", sa.String(length=500), nullable=False),
        sa.Column("is_default", sa.Boolean(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("NOW()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("NOW()"), nullable=False),
        sa.Column("tenant_id", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "user_id", "provider", "name", name="uq_api_key_tenant_user_provider_name"),
    )
    op.create_index("idx_api_keys_provider", "api_keys", ["provider"], unique=False)
    op.create_index("idx_api_keys_tenant_id", "api_keys", ["tenant_id"], unique=False)
    op.create_index("idx_api_keys_user_id", "api_keys", ["user_id"], unique=False)
    op.create_index(op.f("ix_api_keys_provider"), "api_keys", ["provider"], unique=False)
    op.create_index(op.f("ix_api_keys_tenant_id"), "api_keys", ["tenant_id"], unique=False)
    op.create_index(op.f("ix_api_keys_user_id"), "api_keys", ["user_id"], unique=False)
    op.create_table(
        "artifacts",
        sa.Column("meeting_id", sa.String(length=36), nullable=False),
        sa.Column("project_id", sa.String(length=36), nullable=True),
        sa.Column("type", sa.String(length=50), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=True),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("content", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("content_ref", sa.String(length=500), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("parent_id", sa.String(length=36), nullable=True),
        sa.Column(
            "source_artifact_ids",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column("created_by", sa.String(length=100), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("NOW()"), nullable=False),
        sa.Column("tenant_id", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("meeting_id", "type", "version", name="uq_artifacts_meeting_type_version"),
    )
    op.create_index("idx_artifacts_meeting", "artifacts", ["meeting_id"], unique=False)
    op.create_index("idx_artifacts_tenant", "artifacts", ["tenant_id"], unique=False)
    op.create_index("idx_artifacts_type", "artifacts", ["type"], unique=False)
    op.create_index(op.f("ix_artifacts_tenant_id"), "artifacts", ["tenant_id"], unique=False)
    op.create_table(
        "audit_logs",
        sa.Column("timestamp", sa.String(length=40), nullable=False, comment="ISO8601 UTC 时间戳"),
        sa.Column("category", sa.String(length=20), nullable=False),
        sa.Column("action", sa.String(length=50), nullable=False),
        sa.Column("user_id", sa.String(length=64), nullable=False),
        sa.Column("username", sa.String(length=128), nullable=False),
        sa.Column("user_role", sa.String(length=30), nullable=False),
        sa.Column("meeting_id", sa.String(length=36), nullable=False),
        sa.Column("request_id", sa.String(length=64), nullable=False),
        sa.Column("ip", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("details", sa.Text(), nullable=False),
        sa.Column("duration_ms", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_audit_action", "audit_logs", ["action"], unique=False)
    op.create_index("idx_audit_category", "audit_logs", ["category"], unique=False)
    op.create_index("idx_audit_meeting", "audit_logs", ["meeting_id"], unique=False)
    op.create_index("idx_audit_time", "audit_logs", ["timestamp"], unique=False)
    op.create_index("idx_audit_user", "audit_logs", ["username"], unique=False)
    op.create_index(op.f("ix_audit_logs_action"), "audit_logs", ["action"], unique=False)
    op.create_index(op.f("ix_audit_logs_category"), "audit_logs", ["category"], unique=False)
    op.create_index(op.f("ix_audit_logs_meeting_id"), "audit_logs", ["meeting_id"], unique=False)
    op.create_index(op.f("ix_audit_logs_timestamp"), "audit_logs", ["timestamp"], unique=False)
    op.create_index(op.f("ix_audit_logs_username"), "audit_logs", ["username"], unique=False)
    op.create_table(
        "chunk_entities",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("meeting_id", sa.String(length=36), nullable=False),
        sa.Column("doc_id", sa.String(length=36), nullable=False),
        sa.Column("chunk_id", sa.String(length=120), nullable=False),
        sa.Column("entity_id", sa.String(length=36), nullable=False),
        sa.Column("salience", sa.Float(), nullable=False),
        sa.Column("tenant_id", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("chunk_id", "entity_id", name="uq_chunk_entity"),
    )
    op.create_index("idx_chunk_entities_chunk", "chunk_entities", ["chunk_id"], unique=False)
    op.create_index("idx_chunk_entities_entity", "chunk_entities", ["entity_id"], unique=False)
    op.create_index("idx_chunk_entities_tenant", "chunk_entities", ["tenant_id"], unique=False)
    op.create_index(op.f("ix_chunk_entities_chunk_id"), "chunk_entities", ["chunk_id"], unique=False)
    op.create_index(op.f("ix_chunk_entities_doc_id"), "chunk_entities", ["doc_id"], unique=False)
    op.create_index(op.f("ix_chunk_entities_entity_id"), "chunk_entities", ["entity_id"], unique=False)
    op.create_index(op.f("ix_chunk_entities_meeting_id"), "chunk_entities", ["meeting_id"], unique=False)
    op.create_index(op.f("ix_chunk_entities_tenant_id"), "chunk_entities", ["tenant_id"], unique=False)
    op.create_table(
        "cost_records",
        sa.Column("meeting_id", sa.String(length=36), nullable=True),
        sa.Column("stage", sa.String(length=30), nullable=False),
        sa.Column("node", sa.String(length=50), nullable=False, comment="调用节点: llm|tool|sandbox"),
        sa.Column("role", sa.String(length=50), nullable=False),
        sa.Column("provider", sa.String(length=50), nullable=False),
        sa.Column("model", sa.String(length=100), nullable=False),
        sa.Column("tool_name", sa.String(length=100), nullable=False),
        sa.Column("input_tokens", sa.Integer(), nullable=False),
        sa.Column("output_tokens", sa.Integer(), nullable=False),
        sa.Column("cost_usd", sa.Float(), nullable=False),
        sa.Column("latency_ms", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("error", sa.Text(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("NOW()"), nullable=False),
        sa.Column("tenant_id", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_cost_created", "cost_records", ["created_at"], unique=False)
    op.create_index("idx_cost_meeting", "cost_records", ["meeting_id"], unique=False)
    op.create_index("idx_cost_node", "cost_records", ["node"], unique=False)
    op.create_index(op.f("ix_cost_records_meeting_id"), "cost_records", ["meeting_id"], unique=False)
    op.create_index(op.f("ix_cost_records_tenant_id"), "cost_records", ["tenant_id"], unique=False)
    op.create_table(
        "docker_host_secrets",
        sa.Column("host_id", sa.Integer(), nullable=False),
        sa.Column("ssh_password", sa.Text(), nullable=False),
        sa.Column("ssh_key_content", sa.Text(), nullable=False),
        sa.Column("tls_cert_content", sa.Text(), nullable=False),
        sa.Column("tls_key_content", sa.Text(), nullable=False),
        sa.Column("tls_ca_content", sa.Text(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("tenant_id", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("host_id"),
    )
    op.create_index(op.f("ix_docker_host_secrets_tenant_id"), "docker_host_secrets", ["tenant_id"], unique=False)
    op.create_table(
        "docker_hosts",
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("connection_type", sa.String(length=20), nullable=False),
        sa.Column("docker_host", sa.String(length=500), nullable=False),
        sa.Column("ssh_user", sa.String(length=100), nullable=False),
        sa.Column("ssh_port", sa.Integer(), nullable=False),
        sa.Column("ssh_key_path", sa.String(length=500), nullable=False),
        sa.Column("tls_cert_path", sa.String(length=500), nullable=False),
        sa.Column("tls_key_path", sa.String(length=500), nullable=False),
        sa.Column("tls_ca_path", sa.String(length=500), nullable=False),
        sa.Column("tls_verify", sa.Boolean(), nullable=False),
        sa.Column("tags", sa.JSON(), nullable=False),
        sa.Column("region", sa.String(length=50), nullable=False),
        sa.Column("cpu_cores", sa.Integer(), nullable=False),
        sa.Column("memory_gb", sa.Integer(), nullable=False),
        sa.Column("max_containers", sa.Integer(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("is_default", sa.Boolean(), nullable=False),
        sa.Column("health_status", sa.String(length=20), nullable=False),
        sa.Column("last_health_check", sa.DateTime(timezone=True), nullable=True),
        sa.Column("docker_version", sa.String(length=50), nullable=False),
        sa.Column("running_containers", sa.Integer(), nullable=False),
        sa.Column("total_containers", sa.Integer(), nullable=False),
        sa.Column("last_error", sa.Text(), nullable=False),
        sa.Column("deployed_meetings", sa.JSON(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("NOW()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("NOW()"), nullable=False),
        sa.Column("tenant_id", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "name", name="uq_docker_host_tenant_name"),
    )
    op.create_index(op.f("ix_docker_hosts_tenant_id"), "docker_hosts", ["tenant_id"], unique=False)
    op.create_table(
        "document_relations",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("src_doc_id", sa.String(length=36), nullable=False),
        sa.Column("dst_doc_id", sa.String(length=36), nullable=False),
        sa.Column("relation_type", sa.String(length=20), nullable=False),
        sa.Column("score", sa.Float(), nullable=False),
        sa.Column("created_by", sa.String(length=20), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("tenant_id", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("src_doc_id", "dst_doc_id", "relation_type", name="uq_doc_relation"),
    )
    op.create_index("idx_doc_relations_dst", "document_relations", ["dst_doc_id"], unique=False)
    op.create_index("idx_doc_relations_src", "document_relations", ["src_doc_id"], unique=False)
    op.create_index("idx_doc_relations_tenant", "document_relations", ["tenant_id"], unique=False)
    op.create_index(op.f("ix_document_relations_dst_doc_id"), "document_relations", ["dst_doc_id"], unique=False)
    op.create_index(op.f("ix_document_relations_src_doc_id"), "document_relations", ["src_doc_id"], unique=False)
    op.create_index(op.f("ix_document_relations_tenant_id"), "document_relations", ["tenant_id"], unique=False)
    op.create_table(
        "entities",
        sa.Column("meeting_id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("name_norm", sa.String(length=200), nullable=False),
        sa.Column("entity_type", sa.String(length=50), nullable=False),
        sa.Column("mention_count", sa.Integer(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("NOW()"), nullable=False),
        sa.Column("tenant_id", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "name_norm", name="uq_entity_tenant_name"),
    )
    op.create_index("idx_entities_meeting", "entities", ["meeting_id"], unique=False)
    op.create_index("idx_entities_tenant", "entities", ["tenant_id"], unique=False)
    op.create_index(op.f("ix_entities_meeting_id"), "entities", ["meeting_id"], unique=False)
    op.create_index(op.f("ix_entities_name_norm"), "entities", ["name_norm"], unique=False)
    op.create_index(op.f("ix_entities_tenant_id"), "entities", ["tenant_id"], unique=False)
    op.create_table(
        "events",
        sa.Column("seq", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("meeting_id", sa.String(length=36), nullable=False),
        sa.Column("type", sa.String(length=50), nullable=False),
        sa.Column("payload", sa.Text(), nullable=False),
        sa.Column("ts", sa.DateTime(timezone=True), nullable=False),
        sa.Column("trace_id", sa.String(length=36), nullable=True),
        sa.Column("tenant_id", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("seq"),
    )
    op.create_index("idx_events_meeting", "events", ["meeting_id"], unique=False)
    op.create_index("idx_events_meeting_seq", "events", ["meeting_id", "seq"], unique=False)
    op.create_index(op.f("ix_events_tenant_id"), "events", ["tenant_id"], unique=False)
    op.create_table(
        "feature_memories",
        sa.Column("agent_role", sa.String(length=50), nullable=False),
        sa.Column("feature_type", sa.String(length=30), nullable=False),
        sa.Column("feature_value", sa.String(length=50), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("sample_count", sa.Integer(), nullable=False),
        sa.Column("source_meeting_ids", sa.Text(), nullable=False),
        sa.Column("extracted_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_feature_memories_agent", "feature_memories", ["agent_role"], unique=False)
    op.create_index(op.f("ix_feature_memories_agent_role"), "feature_memories", ["agent_role"], unique=False)
    op.create_index(op.f("ix_feature_memories_tenant_id"), "feature_memories", ["tenant_id"], unique=False)
    op.create_table(
        "graph_edges",
        sa.Column("meeting_id", sa.String(length=36), nullable=False),
        sa.Column("source_type", sa.String(length=20), nullable=False),
        sa.Column("source_id", sa.String(length=120), nullable=False),
        sa.Column("target_type", sa.String(length=20), nullable=False),
        sa.Column("target_id", sa.String(length=120), nullable=False),
        sa.Column("relation_type", sa.String(length=20), nullable=False),
        sa.Column("weight", sa.Float(), nullable=False),
        sa.Column("evidence_id", sa.String(length=120), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("NOW()"), nullable=False),
        sa.Column("tenant_id", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "meeting_id", "source_type", "source_id", "target_type", "target_id", "relation_type", name="uq_graph_edge"
        ),
    )
    op.create_index("idx_graph_edges_meeting", "graph_edges", ["meeting_id"], unique=False)
    op.create_index("idx_graph_edges_relation", "graph_edges", ["relation_type"], unique=False)
    op.create_index("idx_graph_edges_tenant", "graph_edges", ["tenant_id"], unique=False)
    op.create_index(op.f("ix_graph_edges_meeting_id"), "graph_edges", ["meeting_id"], unique=False)
    op.create_index(op.f("ix_graph_edges_tenant_id"), "graph_edges", ["tenant_id"], unique=False)
    op.create_table(
        "issues",
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("body", sa.Text(), nullable=True),
        sa.Column("source", sa.String(length=20), nullable=False),
        sa.Column("source_meeting_id", sa.String(length=36), nullable=True),
        sa.Column("status", sa.String(length=20), server_default=sa.text("'open'"), nullable=False),
        sa.Column("priority", sa.Integer(), server_default=sa.text("50"), nullable=False),
        sa.Column("assigned_meeting_id", sa.String(length=36), nullable=True),
        sa.Column("resolution_artifact_id", sa.String(length=36), nullable=True),
        sa.Column("created_by", sa.String(length=100), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("NOW()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("NOW()"), nullable=False),
        sa.Column("tenant_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["resolution_artifact_id"], ["artifacts.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_issues_project", "issues", ["project_id"], unique=False)
    op.create_index("idx_issues_status", "issues", ["status"], unique=False)
    op.create_index("idx_issues_tenant", "issues", ["tenant_id"], unique=False)
    op.create_index(op.f("ix_issues_tenant_id"), "issues", ["tenant_id"], unique=False)
    op.create_table(
        "knowledge_spaces",
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("scope", sa.String(length=20), nullable=False),
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.Column("is_default", sa.Boolean(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("NOW()"), nullable=False),
        sa.Column("tenant_id", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_knowledge_spaces_tenant", "knowledge_spaces", ["tenant_id"], unique=False)
    op.create_index(
        "idx_knowledge_spaces_tenant_default", "knowledge_spaces", ["tenant_id", "is_default"], unique=False
    )
    op.create_index(op.f("ix_knowledge_spaces_tenant_id"), "knowledge_spaces", ["tenant_id"], unique=False)
    op.create_table(
        "meeting_document_refs",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("meeting_id", sa.String(length=36), nullable=False),
        sa.Column("document_id", sa.String(length=36), nullable=False),
        sa.Column("added_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("added_by", sa.String(length=100), nullable=False),
        sa.Column("tenant_id", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_mdr_meeting_doc", "meeting_document_refs", ["meeting_id", "document_id"], unique=True)
    op.create_index("idx_mdr_tenant", "meeting_document_refs", ["tenant_id"], unique=False)
    op.create_index(
        op.f("ix_meeting_document_refs_document_id"), "meeting_document_refs", ["document_id"], unique=False
    )
    op.create_index(op.f("ix_meeting_document_refs_meeting_id"), "meeting_document_refs", ["meeting_id"], unique=False)
    op.create_index(op.f("ix_meeting_document_refs_tenant_id"), "meeting_document_refs", ["tenant_id"], unique=False)
    op.create_table(
        "meetings",
        sa.Column("topic", sa.String(length=500), nullable=False),
        sa.Column("owner_username", sa.String(length=100), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False, comment="running|paused|aborted|done|deleted"),
        sa.Column(
            "stage",
            sa.String(length=20),
            nullable=False,
            comment="clarify|intra_team|cross_team|evidence_check|arbitrate|produce",
        ),
        sa.Column("payload", sa.Text(), nullable=False),
        sa.Column("schema_version", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.String(length=36), nullable=True),
        sa.Column("issue_id", sa.String(length=36), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("NOW()"), nullable=False),
        sa.Column("tenant_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["issue_id"], ["issues.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_meetings_created", "meetings", ["created_at"], unique=False)
    op.create_index("idx_meetings_status", "meetings", ["status"], unique=False)
    op.create_index(op.f("ix_meetings_owner_username"), "meetings", ["owner_username"], unique=False)
    op.create_index(op.f("ix_meetings_tenant_id"), "meetings", ["tenant_id"], unique=False)
    op.create_table(
        "profile_memories",
        sa.Column("agent_role", sa.String(length=50), nullable=False),
        sa.Column("default_stance_style", sa.String(length=20), nullable=False),
        sa.Column("ambiguity_tolerance", sa.Float(), nullable=False),
        sa.Column("evidence_dependency_level", sa.String(length=20), nullable=False),
        sa.Column("collaboration_preference", sa.String(length=20), nullable=False),
        sa.Column("escalation_threshold", sa.Float(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("NOW()"), nullable=False),
        sa.Column("tenant_id", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_profile_memories_agent_role"), "profile_memories", ["agent_role"], unique=False)
    op.create_index(op.f("ix_profile_memories_tenant_id"), "profile_memories", ["tenant_id"], unique=False)
    op.create_table(
        "projects",
        sa.Column("slug", sa.String(length=100), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("repo_url", sa.String(length=500), nullable=True),
        sa.Column("default_branch", sa.String(length=200), server_default=sa.text("'main'"), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("created_by", sa.String(length=100), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("NOW()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("NOW()"), nullable=False),
        sa.Column("tenant_id", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "slug", name="uq_projects_tenant_slug"),
    )
    op.create_index("idx_projects_slug", "projects", ["slug"], unique=False)
    op.create_index("idx_projects_tenant", "projects", ["tenant_id"], unique=False)
    op.create_index(op.f("ix_projects_tenant_id"), "projects", ["tenant_id"], unique=False)
    op.create_table(
        "raw_memories",
        sa.Column("agent_role", sa.String(length=50), nullable=False),
        sa.Column("meeting_id", sa.String(length=36), nullable=False),
        sa.Column("stage", sa.String(length=20), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("evidence_refs", sa.Text(), nullable=False),
        sa.Column("adopted", sa.Boolean(), nullable=False),
        sa.Column("corrected_by", sa.String(length=50), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("NOW()"), nullable=False),
        sa.Column("tenant_id", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_raw_memories_agent", "raw_memories", ["agent_role"], unique=False)
    op.create_index("idx_raw_memories_meeting", "raw_memories", ["meeting_id"], unique=False)
    op.create_index(op.f("ix_raw_memories_agent_role"), "raw_memories", ["agent_role"], unique=False)
    op.create_index(op.f("ix_raw_memories_tenant_id"), "raw_memories", ["tenant_id"], unique=False)
    op.create_table(
        "tenant_members",
        sa.Column("tenant_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column(
            "role",
            sa.String(length=20),
            server_default=sa.text("'member'"),
            nullable=False,
            comment="Team级角色: owner/maintainer/member/reporter/banned",
        ),
        sa.Column("is_banned", sa.Boolean(), server_default=sa.text("FALSE"), nullable=False),
        sa.Column("invited_by", sa.Integer(), nullable=True),
        sa.Column("joined_at", sa.DateTime(timezone=True), server_default=sa.text("NOW()"), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("NOW()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("NOW()"), nullable=False),
        sa.CheckConstraint("role IN ('owner','maintainer','member','reporter','banned')", name="ck_tm_role"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "user_id", name="uq_tm_tenant_user"),
    )
    op.create_index("idx_tm_role", "tenant_members", ["role"], unique=False)
    op.create_index(
        "idx_tm_tenant_active_joined",
        "tenant_members",
        ["tenant_id", "joined_at"],
        unique=False,
        postgresql_where=sa.text("is_banned = FALSE"),
    )
    op.create_index("idx_tm_tenant_role", "tenant_members", ["tenant_id", "role"], unique=False)
    op.create_index(op.f("ix_tenant_members_tenant_id"), "tenant_members", ["tenant_id"], unique=False)
    op.create_index(op.f("ix_tenant_members_user_id"), "tenant_members", ["user_id"], unique=False)
    op.create_table(
        "tenants",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("slug", sa.String(length=64), nullable=False),
        sa.Column("plan", sa.String(length=32), server_default=sa.text("'free'"), nullable=False),
        sa.Column("owner_id", sa.Integer(), nullable=True),
        sa.Column("description", sa.Text(), server_default=sa.text("''"), nullable=False),
        sa.Column(
            "settings", postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False
        ),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_tenants_slug"), "tenants", ["slug"], unique=True)
    op.create_table(
        "user_preferences",
        sa.Column("user_id", sa.String(length=50), nullable=False),
        sa.Column("key", sa.String(length=100), nullable=False),
        sa.Column("value", sa.Text(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("NOW()"), nullable=False),
        sa.Column("tenant_id", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("user_id", "key"),
    )
    op.create_index(op.f("ix_user_preferences_tenant_id"), "user_preferences", ["tenant_id"], unique=False)
    op.create_table(
        "user_settings",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("key", sa.String(length=100), nullable=False),
        sa.Column("value", sa.Text(), nullable=False),
        sa.Column("value_type", sa.String(length=20), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("NOW()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("NOW()"), nullable=False),
        sa.CheckConstraint("value_type IN ('string','int','float','bool','json')", name="ck_user_settings_value_type"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "key", name="uq_user_settings_user_key"),
    )
    op.create_index(op.f("ix_user_settings_user_id"), "user_settings", ["user_id"], unique=False)
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("username", sa.String(length=50), nullable=False),
        sa.Column("password_hash", sa.String(length=512), nullable=False),
        sa.Column("display_name", sa.String(length=100), nullable=True),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("role", sa.String(length=20), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("tenant_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("last_login_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_index(op.f("ix_users_tenant_id"), "users", ["tenant_id"], unique=False)
    op.create_index(op.f("ix_users_username"), "users", ["username"], unique=True)
    op.create_table(
        "documents",
        sa.Column("space_id", sa.String(length=36), nullable=True),
        sa.Column("meeting_id", sa.String(length=36), nullable=True),
        sa.Column("filename", sa.String(length=500), nullable=False),
        sa.Column("original_name", sa.String(length=500), nullable=False),
        sa.Column("content_type", sa.String(length=100), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("chunk_count", sa.Integer(), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False, comment="SHA256 of file content for dedup"),
        sa.Column("raw_content", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("recycled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("NOW()"), nullable=False),
        sa.Column("tenant_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["meeting_id"], ["meetings.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_documents_meeting", "documents", ["meeting_id"], unique=False)
    op.create_index("idx_documents_space", "documents", ["space_id"], unique=False)
    op.create_index("idx_documents_status", "documents", ["status"], unique=False)
    op.create_index(op.f("ix_documents_meeting_id"), "documents", ["meeting_id"], unique=False)
    op.create_index(op.f("ix_documents_space_id"), "documents", ["space_id"], unique=False)
    op.create_index(op.f("ix_documents_tenant_id"), "documents", ["tenant_id"], unique=False)
    op.create_table(
        "meeting_aux",
        sa.Column("meeting_id", sa.String(length=36), nullable=False),
        sa.Column(
            "key",
            sa.String(length=50),
            nullable=False,
            comment="aux field name: llm_trace|evidence_set|conclusion_chain|borrowed_agents",
        ),
        sa.Column("value_json", sa.Text(), nullable=False, comment="JSON-serialized aux field value"),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("NOW()"), nullable=False),
        sa.Column("tenant_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["meeting_id"], ["meetings.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("meeting_id", "key"),
    )
    op.create_index("idx_meeting_aux_meeting", "meeting_aux", ["meeting_id"], unique=False)
    op.create_index(op.f("ix_meeting_aux_tenant_id"), "meeting_aux", ["tenant_id"], unique=False)
    op.create_table(
        "meeting_tags",
        sa.Column("meeting_id", sa.String(length=36), nullable=False),
        sa.Column("tag", sa.String(length=100), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("NOW()"), nullable=False),
        sa.Column("tenant_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["meeting_id"], ["meetings.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("meeting_id", "tag", name="uq_meeting_tag"),
    )
    op.create_index("idx_meeting_tags_meeting", "meeting_tags", ["meeting_id"], unique=False)
    op.create_index("idx_meeting_tags_tag", "meeting_tags", ["tag"], unique=False)
    op.create_index(op.f("ix_meeting_tags_tenant_id"), "meeting_tags", ["tenant_id"], unique=False)
    op.create_table(
        "messages",
        sa.Column("meeting_id", sa.String(length=36), nullable=False),
        sa.Column("agent_role", sa.String(length=50), nullable=False),
        sa.Column("stage", sa.String(length=20), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("claim_refs", sa.Text(), nullable=False),
        sa.Column("evidence_refs", sa.Text(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("NOW()"), nullable=False),
        sa.Column("tenant_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["meeting_id"], ["meetings.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_messages_meeting", "messages", ["meeting_id"], unique=False)
    op.create_index(op.f("ix_messages_meeting_id"), "messages", ["meeting_id"], unique=False)
    op.create_index(op.f("ix_messages_tenant_id"), "messages", ["tenant_id"], unique=False)

    # ===== ADR-019: 延迟外键（规避循环引用）=====
    # artifacts/issues/meetings 之间存在循环 FK（meetings↔issues、issues→artifacts→meetings），
    # create_table 阶段无法按依赖顺序满足，故把这三张表的前向外键拆出，
    # 待全部表建完后统一添加，避免 "relation does not exist" 报错。
    op.create_foreign_key("fk_artifacts_meeting", "artifacts", "meetings", ["meeting_id"], ["id"], ondelete="CASCADE")
    op.create_foreign_key("fk_artifacts_project", "artifacts", "projects", ["project_id"], ["id"], ondelete="SET NULL")
    op.create_foreign_key(
        "fk_issues_assigned_meeting", "issues", "meetings", ["assigned_meeting_id"], ["id"], ondelete="SET NULL"
    )
    op.create_foreign_key("fk_issues_project", "issues", "projects", ["project_id"], ["id"], ondelete="CASCADE")
    op.create_foreign_key(
        "fk_issues_source_meeting", "issues", "meetings", ["source_meeting_id"], ["id"], ondelete="SET NULL"
    )
    op.create_foreign_key("fk_meetings_project", "meetings", "projects", ["project_id"], ["id"], ondelete="SET NULL")

    # ===== ADR-019: 原生 raw SQL 表 / 多租户外键 / 补充索引 / 触发器 纳入 baseline =====
    # 以下对象此前由 main.py、ensure_tenants_table、ensure_rbac_tables、init_auth_table
    # 通过 raw SQL 分头创建；ADR-019 收敛 Alembic 为唯一 schema 应用器，全部平移到本迁移。

    # pg_trgm 扩展（users 前缀模糊搜索 GIN 索引依赖，先建扩展）
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")

    # net_auth_requests（网络授权审批，原 app/net_auth.py init_auth_table 建表）
    op.execute(
        """
        CREATE TABLE net_auth_requests (
            id TEXT PRIMARY KEY,
            tenant_id INTEGER,
            meeting_id TEXT NOT NULL,
            stage TEXT NOT NULL,
            code_snippet TEXT NOT NULL,
            requested_level TEXT NOT NULL,
            detected_level TEXT NOT NULL,
            failure_reason TEXT NOT NULL,
            stderr_output TEXT NOT NULL,
            status TEXT NOT NULL DEFAULT 'pending',
            review_action TEXT,
            review_comment TEXT,
            reviewed_at TEXT,
            created_at TEXT NOT NULL,
            expires_at TEXT NOT NULL,
            resolved_at TEXT
        )
        """
    )
    op.execute("CREATE INDEX idx_auth_meeting ON net_auth_requests(meeting_id)")
    op.execute("CREATE INDEX idx_auth_status ON net_auth_requests(status)")
    op.execute("CREATE INDEX idx_auth_tenant ON net_auth_requests(tenant_id)")

    # notifications（通知，原 app/routers/notifications.py _ensure_table 建表）
    # 注：原 DDL user_id 为 BIGINT、meeting_id 为 BIGINT 且内联外键，与 users.id(INTEGER)、
    # meetings.id(VARCHAR(36)) 类型不匹配，外键从未真正建立；baseline 修正为一致类型且
    # 省略外键（保留"不强制外键"的既有运行时语义），避免通知插入任意 meeting_id 被拒绝。
    op.execute(
        """
        CREATE TABLE notifications (
            id BIGSERIAL PRIMARY KEY,
            user_id INTEGER,
            type VARCHAR(32) NOT NULL DEFAULT 'system',
            level VARCHAR(16) NOT NULL DEFAULT 'info',
            title VARCHAR(256) NOT NULL,
            message TEXT NOT NULL,
            meeting_id VARCHAR(36),
            is_read BOOLEAN NOT NULL DEFAULT FALSE,
            created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
        )
        """
    )
    op.execute("CREATE INDEX idx_notifications_user_created ON notifications(user_id, created_at DESC)")
    op.execute("CREATE INDEX idx_notifications_unread ON notifications(user_id, is_read) WHERE is_read = FALSE")

    # system_settings（系统级 KV 配置，原 ensure_rbac_tables §4.5 建表）
    op.execute(
        """
        CREATE TABLE system_settings (
            key VARCHAR(100) PRIMARY KEY,
            value TEXT NOT NULL,
            value_type VARCHAR(20) NOT NULL DEFAULT 'string',
            updated_at TIMESTAMP NOT NULL DEFAULT NOW(),
            created_at TIMESTAMP NOT NULL DEFAULT NOW()
        )
        """
    )
    op.execute(
        "ALTER TABLE system_settings ADD CONSTRAINT ck_system_settings_value_type "
        "CHECK (value_type IN ('string','int','float','bool','json'))"
    )

    # 多租户外键（ORM 有意不声明 FK，原 ensure_tenants_table / ensure_rbac_tables 通过 ALTER 添加）
    op.execute(
        "ALTER TABLE users ADD CONSTRAINT fk_users_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE SET NULL"
    )
    op.execute(
        "ALTER TABLE tenants ADD CONSTRAINT fk_tenants_owner FOREIGN KEY (owner_id) REFERENCES users(id) ON DELETE SET NULL"
    )
    op.execute(
        "ALTER TABLE tenant_members ADD CONSTRAINT fk_tm_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE"
    )
    op.execute(
        "ALTER TABLE tenant_members ADD CONSTRAINT fk_tm_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE"
    )
    op.execute(
        "ALTER TABLE tenant_members ADD CONSTRAINT fk_tm_invited_by FOREIGN KEY (invited_by) REFERENCES users(id) ON DELETE SET NULL"
    )
    op.execute(
        "ALTER TABLE api_keys ADD CONSTRAINT fk_api_keys_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE"
    )
    op.execute(
        "ALTER TABLE user_settings ADD CONSTRAINT fk_user_settings_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE"
    )

    # 补充索引（原 ensure_tenants_table / ensure_rbac_tables 创建）
    op.execute("CREATE INDEX idx_users_is_active ON users(is_active)")
    op.execute("CREATE UNIQUE INDEX idx_users_email ON users(email) WHERE email IS NOT NULL")
    op.execute("CREATE INDEX idx_users_username_trgm ON users USING GIN (username gin_trgm_ops)")
    op.execute("CREATE INDEX idx_users_display_name_trgm ON users USING GIN (display_name gin_trgm_ops)")
    op.execute("CREATE INDEX idx_api_keys_tenant_user ON api_keys(tenant_id, user_id)")

    # updated_at 自动更新触发器（原 ensure_rbac_tables §5 创建）
    op.execute(
        """
        CREATE OR REPLACE FUNCTION update_updated_at_column()
        RETURNS TRIGGER AS $$
        BEGIN
            NEW.updated_at = NOW();
            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql;
        """
    )
    op.execute(
        "CREATE TRIGGER trg_tenant_members_updated_at BEFORE UPDATE ON tenant_members "
        "FOR EACH ROW EXECUTE FUNCTION update_updated_at_column()"
    )
    op.execute(
        "CREATE TRIGGER trg_user_settings_updated_at BEFORE UPDATE ON user_settings "
        "FOR EACH ROW EXECUTE FUNCTION update_updated_at_column()"
    )
    op.execute(
        "CREATE TRIGGER trg_system_settings_updated_at BEFORE UPDATE ON system_settings "
        "FOR EACH ROW EXECUTE FUNCTION update_updated_at_column()"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_messages_tenant_id"), table_name="messages")
    op.drop_index(op.f("ix_messages_meeting_id"), table_name="messages")
    op.drop_index("idx_messages_meeting", table_name="messages")
    op.drop_table("messages")
    op.drop_index(op.f("ix_meeting_tags_tenant_id"), table_name="meeting_tags")
    op.drop_index("idx_meeting_tags_tag", table_name="meeting_tags")
    op.drop_index("idx_meeting_tags_meeting", table_name="meeting_tags")
    op.drop_table("meeting_tags")
    op.drop_index(op.f("ix_meeting_aux_tenant_id"), table_name="meeting_aux")
    op.drop_index("idx_meeting_aux_meeting", table_name="meeting_aux")
    op.drop_table("meeting_aux")
    op.drop_index(op.f("ix_documents_tenant_id"), table_name="documents")
    op.drop_index(op.f("ix_documents_space_id"), table_name="documents")
    op.drop_index(op.f("ix_documents_meeting_id"), table_name="documents")
    op.drop_index("idx_documents_status", table_name="documents")
    op.drop_index("idx_documents_space", table_name="documents")
    op.drop_index("idx_documents_meeting", table_name="documents")
    op.drop_table("documents")
    op.drop_index(op.f("ix_users_username"), table_name="users")
    op.drop_index(op.f("ix_users_tenant_id"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_user_settings_user_id"), table_name="user_settings")
    op.drop_table("user_settings")
    op.drop_index(op.f("ix_user_preferences_tenant_id"), table_name="user_preferences")
    op.drop_table("user_preferences")
    op.drop_index(op.f("ix_tenants_slug"), table_name="tenants")
    op.drop_table("tenants")
    op.drop_index(op.f("ix_tenant_members_user_id"), table_name="tenant_members")
    op.drop_index(op.f("ix_tenant_members_tenant_id"), table_name="tenant_members")
    op.drop_index("idx_tm_tenant_role", table_name="tenant_members")
    op.drop_index(
        "idx_tm_tenant_active_joined", table_name="tenant_members", postgresql_where=sa.text("is_banned = FALSE")
    )
    op.drop_index("idx_tm_role", table_name="tenant_members")
    op.drop_table("tenant_members")
    op.drop_index(op.f("ix_raw_memories_tenant_id"), table_name="raw_memories")
    op.drop_index(op.f("ix_raw_memories_agent_role"), table_name="raw_memories")
    op.drop_index("idx_raw_memories_meeting", table_name="raw_memories")
    op.drop_index("idx_raw_memories_agent", table_name="raw_memories")
    op.drop_table("raw_memories")
    op.drop_index(op.f("ix_projects_tenant_id"), table_name="projects")
    op.drop_index("idx_projects_tenant", table_name="projects")
    op.drop_index("idx_projects_slug", table_name="projects")
    op.drop_table("projects")
    op.drop_index(op.f("ix_profile_memories_tenant_id"), table_name="profile_memories")
    op.drop_index(op.f("ix_profile_memories_agent_role"), table_name="profile_memories")
    op.drop_table("profile_memories")
    op.drop_index(op.f("ix_meetings_tenant_id"), table_name="meetings")
    op.drop_index(op.f("ix_meetings_owner_username"), table_name="meetings")
    op.drop_index("idx_meetings_status", table_name="meetings")
    op.drop_index("idx_meetings_created", table_name="meetings")
    op.drop_table("meetings")
    op.drop_index(op.f("ix_meeting_document_refs_tenant_id"), table_name="meeting_document_refs")
    op.drop_index(op.f("ix_meeting_document_refs_meeting_id"), table_name="meeting_document_refs")
    op.drop_index(op.f("ix_meeting_document_refs_document_id"), table_name="meeting_document_refs")
    op.drop_index("idx_mdr_tenant", table_name="meeting_document_refs")
    op.drop_index("idx_mdr_meeting_doc", table_name="meeting_document_refs")
    op.drop_table("meeting_document_refs")
    op.drop_index(op.f("ix_knowledge_spaces_tenant_id"), table_name="knowledge_spaces")
    op.drop_index("idx_knowledge_spaces_tenant_default", table_name="knowledge_spaces")
    op.drop_index("idx_knowledge_spaces_tenant", table_name="knowledge_spaces")
    op.drop_table("knowledge_spaces")
    op.drop_index(op.f("ix_issues_tenant_id"), table_name="issues")
    op.drop_index("idx_issues_tenant", table_name="issues")
    op.drop_index("idx_issues_status", table_name="issues")
    op.drop_index("idx_issues_project", table_name="issues")
    op.drop_table("issues")
    op.drop_index(op.f("ix_graph_edges_tenant_id"), table_name="graph_edges")
    op.drop_index(op.f("ix_graph_edges_meeting_id"), table_name="graph_edges")
    op.drop_index("idx_graph_edges_tenant", table_name="graph_edges")
    op.drop_index("idx_graph_edges_relation", table_name="graph_edges")
    op.drop_index("idx_graph_edges_meeting", table_name="graph_edges")
    op.drop_table("graph_edges")
    op.drop_index(op.f("ix_feature_memories_tenant_id"), table_name="feature_memories")
    op.drop_index(op.f("ix_feature_memories_agent_role"), table_name="feature_memories")
    op.drop_index("idx_feature_memories_agent", table_name="feature_memories")
    op.drop_table("feature_memories")
    op.drop_index(op.f("ix_events_tenant_id"), table_name="events")
    op.drop_index("idx_events_meeting_seq", table_name="events")
    op.drop_index("idx_events_meeting", table_name="events")
    op.drop_table("events")
    op.drop_index(op.f("ix_entities_tenant_id"), table_name="entities")
    op.drop_index(op.f("ix_entities_name_norm"), table_name="entities")
    op.drop_index(op.f("ix_entities_meeting_id"), table_name="entities")
    op.drop_index("idx_entities_tenant", table_name="entities")
    op.drop_index("idx_entities_meeting", table_name="entities")
    op.drop_table("entities")
    op.drop_index(op.f("ix_document_relations_tenant_id"), table_name="document_relations")
    op.drop_index(op.f("ix_document_relations_src_doc_id"), table_name="document_relations")
    op.drop_index(op.f("ix_document_relations_dst_doc_id"), table_name="document_relations")
    op.drop_index("idx_doc_relations_tenant", table_name="document_relations")
    op.drop_index("idx_doc_relations_src", table_name="document_relations")
    op.drop_index("idx_doc_relations_dst", table_name="document_relations")
    op.drop_table("document_relations")
    op.drop_index(op.f("ix_docker_hosts_tenant_id"), table_name="docker_hosts")
    op.drop_table("docker_hosts")
    op.drop_index(op.f("ix_docker_host_secrets_tenant_id"), table_name="docker_host_secrets")
    op.drop_table("docker_host_secrets")
    op.drop_index(op.f("ix_cost_records_tenant_id"), table_name="cost_records")
    op.drop_index(op.f("ix_cost_records_meeting_id"), table_name="cost_records")
    op.drop_index("idx_cost_node", table_name="cost_records")
    op.drop_index("idx_cost_meeting", table_name="cost_records")
    op.drop_index("idx_cost_created", table_name="cost_records")
    op.drop_table("cost_records")
    op.drop_index(op.f("ix_chunk_entities_tenant_id"), table_name="chunk_entities")
    op.drop_index(op.f("ix_chunk_entities_meeting_id"), table_name="chunk_entities")
    op.drop_index(op.f("ix_chunk_entities_entity_id"), table_name="chunk_entities")
    op.drop_index(op.f("ix_chunk_entities_doc_id"), table_name="chunk_entities")
    op.drop_index(op.f("ix_chunk_entities_chunk_id"), table_name="chunk_entities")
    op.drop_index("idx_chunk_entities_tenant", table_name="chunk_entities")
    op.drop_index("idx_chunk_entities_entity", table_name="chunk_entities")
    op.drop_index("idx_chunk_entities_chunk", table_name="chunk_entities")
    op.drop_table("chunk_entities")
    op.drop_index(op.f("ix_audit_logs_username"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_timestamp"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_meeting_id"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_category"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_action"), table_name="audit_logs")
    op.drop_index("idx_audit_user", table_name="audit_logs")
    op.drop_index("idx_audit_time", table_name="audit_logs")
    op.drop_index("idx_audit_meeting", table_name="audit_logs")
    op.drop_index("idx_audit_category", table_name="audit_logs")
    op.drop_index("idx_audit_action", table_name="audit_logs")
    op.drop_table("audit_logs")
    op.drop_index(op.f("ix_artifacts_tenant_id"), table_name="artifacts")
    op.drop_index("idx_artifacts_type", table_name="artifacts")
    op.drop_index("idx_artifacts_tenant", table_name="artifacts")
    op.drop_index("idx_artifacts_meeting", table_name="artifacts")
    op.drop_table("artifacts")
    op.drop_index(op.f("ix_api_keys_user_id"), table_name="api_keys")
    op.drop_index(op.f("ix_api_keys_tenant_id"), table_name="api_keys")
    op.drop_index(op.f("ix_api_keys_provider"), table_name="api_keys")
    op.drop_index("idx_api_keys_user_id", table_name="api_keys")
    op.drop_index("idx_api_keys_tenant_id", table_name="api_keys")
    op.drop_index("idx_api_keys_provider", table_name="api_keys")
    op.drop_table("api_keys")
    op.drop_index(op.f("ix_agent_roles_tenant_id"), table_name="agent_roles")
    op.drop_index("idx_agent_roles_active", table_name="agent_roles")
    op.drop_table("agent_roles")
    # ### end Alembic commands ###
